baseURL = 'https://www.duclm.dev'
languageCode = 'en-us'
title = "duclm's blog"
theme = "terminal"
#discuss comments
disqusShortname = 'duclm-dev'
[params]
fullWidthTheme = false
centerTheme = true
[menu]
[[menu.main]]
name = 'Blog'
pre = "<i class='fa fa-road'></i>"
url = '/posts'
weight = -110
[[menu.main]]
identifier = 'about'
name = 'About'
pre = "<i class='fa fa-heart'></i>"
url = '/about'
weight = -100
[params.Logo]
logoText = "Le Minh Duc"
